### ISSUE TITLE
AttributeError: module 'PySide2.QtGui' has no attribute 'QRegularExpressionValidator'

### ISSUE THREAD

**Issue by apyrgio** [freedomofpress/dangerzone#339]
Running Dangerzone on Ubuntu Focal from system packages throws the following error:

```python
Traceback (most recent call last):
  File "/usr/bin/dangerzone", line 33, in <module>
    sys.exit(load_entry_point('dangerzone==0.4.0', 'console_scripts', 'dangerzone')())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/dangerzone/errors.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/dangerzone/gui/__init__.py", line 106, in gui_main
    window = MainWindow(dangerzone)
  File "/usr/lib/python3/dist-packages/dangerzone/gui/main_window.py", line 80, in __init__
    self.content_widget = ContentWidget(self.dangerzone)
  File "/usr/lib/python3/dist-packages/dangerzone/gui/main_window.py", line 255, in __init__
    self.settings_widget = SettingsWidget(self.dangerzone)
  File "/usr/lib/python3/dist-packages/dangerzone/gui/main_window.py", line 399, in __init__
    QtGui.QRegularExpressionValidator(dot_pdf_regex)
AttributeError: module 'PySide2.QtGui' has no attribute 'QRegularExpressionValidator'
```

This change was introduced in PR https://github.com/freedomofpress/dangerzone/pull/296 (81e9ccf30a0a527b101461e3bf0d912215809f42). We previously used `QRegExpValidator`, but this class is not present in PySide6. We decided (see https://github.com/freedomofpress/dangerzone/pull/296#discussion_r1067108469) to follow the [docs](https://doc-snapshots.qt.io/qt6-dev/qtcore-changes-qt6.html#the-qregularexpression-class) and replace `QRegExpValidator` with `QRegularExpressionValidator`, which was supposedly present in Qt 5.

It seems though that PySide2 5.14.8 in Ubuntu Focal does not have this class, whereas PySide2 5.15.8 in Debian Bookworm has this.

We need to fallback to the old class (`QRegularExpressionValidator`) in these cases.

**Comment by apyrgio** [comment]
I downloaded the source from the [Debian repo](https://salsa.debian.org/qt-kde-team/qt/pyside2), and I searched for commits that introduce `QRegularExpression` and `QRegularExpressionValidator`:

```
git log -S QRegularExpression
git log -S QRegularExpressionValidator
```

It seems that `QRegularExpression` was introduced in PySide2 5.9, whereas `QRegularExpresssionValidator` was introduced in 5.15.1.

I then looked into the PySide2 versions that are installed in our supported [Ubuntu](https://packages.ubuntu.com/search?keywords=python3-pyside2.qtgui&searchon=names&suite=all&section=all), [Debian](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=python3-pyside2.qtgui), and [Fedora](https://packages.fedoraproject.org/pkgs/python-pyside2/python3-pyside2/) distros.

Besides Ubuntu Focal (5.14), all other distros have PySide2 > 5.15.1. So, we can add for now a fallback to `QRegExpValidator` (present since 5.9) if `QRegularExpressionValidator` does not exist, but we should drop this fallback once we drop support for Ubuntu Focal.
